//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ofis2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demirba
    {
        public int demirbasID { get; set; }
        public string esyaAdi { get; set; }
        public int adet { get; set; }
    }
}
