//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ofis2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gider
    {
        public int giderID { get; set; }
        public string giderAdi { get; set; }
        public string giderMiktari { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string donem { get; set; }
        public string aciklama { get; set; }
    }
}
