//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ofis2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeler
    {
        public int projeID { get; set; }
        public string projeAdi { get; set; }
        public Nullable<System.DateTime> projeBaslangic { get; set; }
        public Nullable<System.DateTime> projeBitis { get; set; }
        public string projeAciklamasi { get; set; }
        public Nullable<int> stajyerID { get; set; }
    
        public virtual StajyerProjeleri StajyerProjeleri { get; set; }
    }
}
