//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ofis2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stajyer
    {
        public int stajyerID { get; set; }
        public string adsoyad { get; set; }
        public string TC { get; set; }
        public string telefonNo { get; set; }
        public string eposta { get; set; }
        public string universite { get; set; }
        public Nullable<System.DateTime> stajBaslangic { get; set; }
        public Nullable<System.DateTime> stajBitis { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual OfisTakvimi OfisTakvimi { get; set; }
        public virtual StajyerProjeleri StajyerProjeleri { get; set; }
        public string TCNO
        {
            get
            {
                return TC;
            }
            set
            {
                if (value.Length == 11)
                    TC = value;
                else
                    throw new Exception("TC numarasý 11 haneli olmalýdýr");
            }
        }
    }
}
